class AppIdentifiers:
    ID_HIGHEST = 5000

    START_SIM_0 = ID_HIGHEST + 1
    START_SIM_1 = ID_HIGHEST + 2
    START_SIM_2 = ID_HIGHEST + 3
    START_SIM_3 = ID_HIGHEST + 4
    START_SIM_4 = ID_HIGHEST + 5
    START_SIM_5 = ID_HIGHEST + 6
    START_SIM_6 = ID_HIGHEST + 7
    START_SIM_7 = ID_HIGHEST + 8
    START_SIM_8 = ID_HIGHEST + 9
    START_SIM_9 = ID_HIGHEST + 10

    START_MY_SIM = ID_HIGHEST + 11

    FILE_LOAD = START_MY_SIM + 10
    FILE_SAVE = START_MY_SIM + 11

    DISPLAY_ANIMATS = ID_HIGHEST + 51
    DISPLAY_OBJECTS = ID_HIGHEST + 52
    DISPLAY_TRAILS = ID_HIGHEST + 53
    DISPLAY_COLLISIONS = ID_HIGHEST + 54
    DISPLAY_SENSORS = ID_HIGHEST + 55
    DISPLAY_MONITOR = ID_HIGHEST + 56

    SIMULATION_PAUSE = ID_HIGHEST + 61
    SIMULATION_RESUME = ID_HIGHEST + 62
    SIMULATION_RESET = ID_HIGHEST + 63
    SIMULATION_FAST = ID_HIGHEST + 64
    SIMULATION_SAVE = ID_HIGHEST + 65

    DEMOS = ID_HIGHEST + 1
    ABOUT = ID_HIGHEST + 81
    MAIN_TIME = ID_HIGHEST + 101
